### ISSUE TITLE
Error after RUN

### ISSUE THREAD

**Issue by Shaxmatist** [dmnsgn/sublime-stylefmt#12]
I use Node 6+
```
Stylefmt
Error: path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at newParmas (/home/shaxmatist/.config/sublime-text-3/Packages/Stylefmt/node_modules/stylefmt/lib/params.js:53:17)
    at /home/shaxmatist/.config/sublime-text-3/Packages/Stylefmt/node_modules/stylefmt/index.js:12:16
    at creator (/home/shaxmatist/.config/sublime-text-3/Packages/Stylefmt/node_modules/postcss/lib/postcss.js:60:39)
    at Function.postcss.plugin (/home/shaxmatist/.config/sublime-text-3/Packages/Stylefmt/node_modules/postcss/lib/postcss.js:66:23)
    at Object.<anonymous> (/home/shaxmatist/.config/sublime-text-3/Packages/Stylefmt/node_modules/stylefmt/index.js:11:24)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/shaxmatist/.config/sublime-text-3/Packages/Stylefmt/stylefmt.js:3:16)
    at Module._compile (module.js:541:32)
```

**Comment by wroughtec** [comment]
Getting the same error

**Comment by dmnsgn** [comment]
Just updated to v4.0.0 of the Stylefmt module. If you are still having this issue, try using the CLI tool (https://github.com/morishitter/stylefmt#installation) and if it still throws this error, try to open an issue on the main repo (https://github.com/morishitter/stylefmt/issues)
